src/main/resources/application-local.yaml, src/main/resources/application.yaml
- `application.yaml` 방언 설정 추가 
- 기본 application 설정정보 변경 
- `application-local.yaml` scheme 변경
=> fix: application 설정정보 수정

build.gradle, src/main/java/com/aroom/global/error/ErrorCode.java, src/main/java/com/aroom/global/error/GlobalExceptionHandler.java, src/main/java/com/aroom/global/error/ServiceException.java, src/main/java/com/aroom/global/response/ApiResponse.java
- ApiResponse.java 추가
- ServiceException.java 추가
- lombok, validation 라이브러리 추가.
- 모든 API들은 `ApiResponse.java` 으로 한번 감싼 후 반환을 해야 합니다.
=> feat: global exception handling 추가

build.gradle, src/main/java/com/aroom/global/jwt/JwtPayload.java, src/main/java/com/aroom/global/jwt/JwtUtils.java, src/main/resources/application-local.yaml, src/test/java/com/aroom/global/jwt/JwtUtilsTest.java, src/test/resources/application.yaml
- `Jjwt` 의존성 추가
- `JwtUtil` 추가
=> ƒeat: JWT 발급 유틸 클래스 추가

src/test/java/com/aroom/domain/reservation/repository/ReservationRepositoryTest.java
예약 기능의 Repository인 ReservationRepository를 테스트 하기 위한 테스트 코드를 작성했습니다.
=> test: 예약 기능 repository 테스트 코드 작성

.github/workflows/CI.yml
빌드, 테스트, 문서화 자동화를 적용을 위한 CI.yml 파일을 작성했습니다.
gradle 빌드, 테스트, 문서화, 코멘트 자동화 기능을 포함하였습니다.
=> chore: CI.yml 작성

src/main/java/com/aroom/domain/member/controller/MemberController.java, src/main/java/com/aroom/domain/member/dto/request/SignUpRequest.java, src/main/java/com/aroom/domain/member/exception/MemberEmailDuplicateException.java, src/main/java/com/aroom/domain/member/model/Member.java, src/main/java/com/aroom/domain/member/repository/MemberRepository.java, src/main/java/com/aroom/domain/member/service/MemberService.java, src/main/java/com/aroom/global/error/ErrorCode.java, src/test/java/com/aroom/domain/member/controller/MemberControllerTest.java, src/test/java/com/aroom/domain/member/service/MemberServiceTest.java
- `member` controller, service layer 추가
- 예외처리는 이후 리팩토링될 예정입니다.
=> ƒeat: 회원가입 기능 추가

src/main/java/com/aroom/global/config/JpaConfig.java, src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java
충돌 해결을 위해 JpaConfig 파일 재 생성
AccommodationRestController 파일 수정
=> fix/ 충돌 해결

src/test/java/com/aroom/global/basetime/BaseTimeEntityTest.java
jpa auditing 테스트를 위해 설정 파일 불러오는 어노테이션을 추가했습니다.
=> test: auditing config 설정 어노테이션 추가

src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java, src/main/java/com/aroom/global/security/SecurityConfig.java, src/main/java/com/aroom/global/security/SecurityFilterConfig.java
- SecurityConfig.java 수정
- SecurityFilterConfig security 적용 범위 수정
=> hotfix: spring security 수정

src/main/java/com/aroom/domain/reservationRoom/model/ReservationRoom.java, src/main/java/com/aroom/domain/room/model/Room.java, src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
motivation:
- 테이블 구조 변경으로 인한 엔티티를 수정했습니다. modification:
- RoomProduct 엔티티를 수정하고, 연관관계를 수정했습니다.
=> feat : 엔티티 구조 수정

build.gradle, src/test/java/com/aroom/docs/CommonDocsController.java, src/test/java/com/aroom/docs/CommonDocsTest.java, src/test/java/com/aroom/docs/RestDocsSupport.java
- Spring Rest Docs 의존성 추가
- CommonDocsTest 추가
=> feat: spring rest docs 추가

src/docs/asciidoc/jwt/jwt-api.adoc, src/main/java/com/aroom/global/jwt/controller/JwtRefreshRestController.java, src/test/java/com/aroom/global/jwt/docs/JwtRefreshRestControllerDocsTest.java
- `JwtRefreshRestControllerDocsTest.java` 추가
=> feat: AccessToken 재발급 API 문서화

src/test/java/com/aroom/util/ControllerTestWithoutSecurityHelper.java
- `ControllerTestWithoutSecurityHelper` 업데이트
=> fix: 누락된 ControllerTestWithoutSecurityHelper 업데이트

src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java, src/test/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerTest.java
Controller 테스트 코드 작성 시 @WithMockAccountContext 가 필요하게 되어 수정하였습니다.
=> fix: controller 테스트 코드 수정

src/main/java/com/aroom/domain/accommodation/dto/AccommodationListResponse.java, src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java, src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
AccommodationControllerTest와 AccommodationServiceTest를 작성했습니다.
AccommodationControllerTest는 Result에 Body 부분이 null 값이 들어가있는 이슈가 있습니다.
=> Feat/#73 숙소 조회 컨트롤러, 서비스 테스트

src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java, src/main/java/com/aroom/domain/accommodation/dto/AccommodationListResponse.java, src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java, src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java, src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java
컨트롤러에서 쿼리스트링 null 체크 로직에 오류가 있었습니다.
기본적으로 page와 size는 default로 0과 10을 할당하는데 null 체크를 이중으로 해서 오류가 발생했습니다.
오류를 해결하고 테스트코드 작성하였습니다.
=> Fix /#73 컨트롤러 로직 오류 수정 및 테스트 코드 작성

src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryCustom.java, src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java, src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java, src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
orderBy가 포함된 쿼리문과 포함되지 않은 쿼리문으로 분기하는 조건절에 오류가 있어 수정했습니다.
=> Hotfix : orderBy분기 if문 조건절 오류 수정

src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerAdvice.java, src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java
startDate는 항상 endDate보다 일러야 하기 때문에 예외처리를 추가했습니다.
=> fix/startDate endDate 예외처리

src/docs/asciidoc/index.adoc
- 토큰 재발급 API 페이지 추가
- 주문 API 페이지 추가
- 장바구니 API 페이지 추가
=> document: rest docs page 추가

src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java, src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
장바구니 추가시 에러를 해결했습니다.
가장 작은 수량의 데이터를 불러오는 부분을 수정했습니다.
=> fix: 장바구니 추가 api 수정

src/main/java/com/aroom/domain/accommodation/dto/SearchCondition.java, src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java, src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
정렬시 Pagination이 안되는 오류가 있었는데, Distinct를 붙여 해결하였습니다.
AccommodationServiceTest 오류 수정하여 테스트 통과하도록 수정했습니다.
=> Hotfix/#73 정렬조건에서 Pagination 오류 버그 수정

src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java
사용하지 않는 검색조건으로 인한 검증 로직 수정하였습니다.
=> Hotfix : 사용하지 않는 검색조건으로 인한 검증 로직 수정

src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java, src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
예약시 request의 구조가 변경되었습니다.
room 별로 personnel 을 받도록 변경하여 맞춰서 수정했습니다.
=> fix: reservation 테스트 코드 수정

src/test/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerTest.java, src/test/java/com/aroom/domain/roomCart/docs/RoomCartRestControllerDocsTest.java, src/test/java/com/aroom/domain/roomCart/service/RoomCartServiceTest.java, src/test/java/com/aroom/domain/roomProduct/repository/RoomProductRepositoryTest.java
roomCart 의 personnel 정보 추가해서 test코드도 함께 수정했습니다.
restDocs도 함께 수정했습니다
=> fix: roomCart test code fix

src/main/java/com/aroom/domain/reservation/service/ReservationService.java
예약시 마지막 날짜는 제외해야 하므로 뻈습니다
reservationService 에서 findRoomProduct 하는 부분에서 endDate에 하루를 빼도록 변경했습니다.
=> fix: reservation 저장시 endDate 수정

src/docs/asciidoc/index.adoc, src/docs/asciidoc/reservations/reservations-api.adoc, src/test/java/com/aroom/domain/accommodation/docs/AccommodationControllerDocsTest.java, src/test/java/com/aroom/domain/reservation/docs/ReservationControllerDocsTest.java, src/test/java/com/aroom/util/fixture/AccommodationResponseFixture.java, src/test/java/com/aroom/util/fixture/JwtFixture.java, src/test/java/com/aroom/util/fixture/ReservationFixture.java
- 누락된 주문 rest docs 추가합니다.
- `reservations-api.adoc` 추가
=> docs: 누락된 주문 rest docs 추가

src/main/java/com/aroom/domain/reservation/service/ReservationService.java, src/main/java/com/aroom/domain/room/repository/RoomImageRepository.java
예약 기능에서 Room의 정보를 반환할 때 image를 잘못된 id값으로 조회하여 반환해주고 있었습니다.
따라서 roomId 로 조회하도록 변경했습니다.
=> fix: reservation room image 수정

src/main/java/com/aroom/domain/reservation/service/ReservationService.java, src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
방 이미지 가져 올 때 없을 경우 빈 값을 반환하게 수정 했습니다. 테스트 코드도 함께 수정되었습니다.
=> fix: 방 이미지 가져오기 수정

src/docs/asciidoc/accommodations/accommodations-api.adoc, src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java, src/test/java/com/aroom/domain/accommodation/docs/AccommodationRestControllerDocsTest.java
=> feat : 숙소 전체 조회 및 필터링 조회 restDocs 작성

src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
장바구니 조회시 동일한 날짜, 방이 여러개 담겨있는 경우 하나로만 보여주던 오류를 고쳤습니다.
날짜별로 정렬했던 것을 삭제했고, 시작 날짜 종료 날짜가 이상하게 삽입 되던 것을 고쳤습니다.
personnel 관련 기능도 수정했습니다.
=> fix: 장바구니 조회 기능 오류 수정

src/main/java/com/aroom/domain/room/dto/response/CartRoomResponse.java, src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
장바구니 상품 선택시에 필요한 roomCartId를 함께 응답하도록 변경했습니다.
=> feat: 장바구니 조회시  roomCartId도 함께 조회

src/test/java/com/aroom/domain/roomCart/docs/RoomCartRestControllerDocsTest.java
=> fix: 장바구니 조회 REST Docs 수정

src/main/java/com/aroom/global/security/SecurityFilterConfig.java
웹 페이지 url로 접속이 안되어 security 설정을 변경해서 고쳤습니다.
=> fix: security 웹 접속 페이지 url 허용

src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java
프론트 엔드 무한 스크롤 기능에 맞추어 잘 동작하도록 limit, offset을 수정하였습니다.
=> fix : Pagination 오류 수정
